platform :ios, '11.4'

target 'NetworkingExample' do
  use_frameworks!

  pod 'Networking', :path => '../'

  target 'NetworkingExampleTests' do
    inherit! :search_paths
    
    pod 'Quick', '~> 1.3.0'
    pod 'Nimble', '~> 7.1.2'
  end

end
