platform :ios, '11.4'

target 'C0T0Example' do
  use_frameworks!

  pod 'C0T0', :path => '../'

  target 'C0T0ExampleTests' do
    inherit! :search_paths
    
    pod 'Quick', '~> 1.3.0'
    pod 'Nimble', '~> 7.1.2'
  end

end
