platform :ios, '11.4'

target 'C0T0Example' do
  use_frameworks!

  pod 'C0T0', :path => '../'

  target 'C0T0ExampleTests' do
    inherit! :search_paths
    
    pod 'Quick', '~> 2.1'
    pod 'Nimble', '~> 8.0'
  end

end
